name: Deploy to GitHub Pages

permissions:
  contents: write
  
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy files with excludes
        run: |
          mkdir -p deploy_dir
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='dem/*.json'  --exclude='data/' . deploy_dir/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_dir
