name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files with excludes
        run: |
          mkdir -p deploy_dir
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='dem/*.json' . deploy_dir/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_dir
